name: TESTESTTEST

on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from develop to main"
          base: main
          branch: develop
          title: "Daily Merge changes from develop to main"
          body: |
            This PR merges the latest changes from the `develop` branch into the `main` branch.
          draft: false
