name: ZAP scan

on:
  push:
    branches:
      - develop
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://uvlhub-delsanrub.onrender.com/'
